parameters:
#    eve_corp_center_site.example.class: EVECorpCenter\SiteBundle\Example

services:
#    eve_corp_center_site.example:
#        class: %eve_corp_center_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
